apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: docker-test-app
        image: darrenjones/docker-test-app:latest
        ports:
        - containerPort: 8080
          name: testapp
        resources:
         limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: testapp-service
spec:
  ports:
  - nodePort: 31848
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: testapp
  type: NodePort